<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>6. Supplier Direct LOA - Services</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>838246f2-d245-448e-9e26-15f325183709</testSuiteGuid>
   <testCaseLink>
      <guid>5f4e14a0-6d0c-4437-a8b4-2a2aa4c0aa4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2. DLOA/6. Supplier Direct LOA - Services</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>69ff6fbe-eaf8-44a2-815e-85689a18e458</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DP LOA/6. Supplier Direct LOA - Services</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>69ff6fbe-eaf8-44a2-815e-85689a18e458</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>63053bd3-8895-44cf-a54d-b3a128ddcfb9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>69ff6fbe-eaf8-44a2-815e-85689a18e458</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>5aa9b4dd-ad8c-49a1-82aa-e118813057b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>69ff6fbe-eaf8-44a2-815e-85689a18e458</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Document_Number</value>
         <variableId>150a398d-723d-40d3-8205-37a8ec612310</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e66f4bf-167c-48e5-ad8b-c732a2275348</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>390e3ed7-2c2c-43fe-aa89-5331463f5b0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44a80664-f54a-48ee-974a-c0b821655852</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b290f551-59ad-4c5f-b518-2c325ccad01d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88ce4fe5-c806-4c7b-a6fe-f615f4e1f888</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80d047db-08e5-40e0-a4fc-de821e927401</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>415d2e18-60b1-4932-b8dd-ed9bbd7f0716</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e6a2004-17ba-4f94-a6b3-7342efa2a266</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2feba6f1-1d89-4458-aeb6-ee92270a6cb3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcccf8e4-391b-43be-ad86-5b0ff3bec43a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae67303f-a040-47a3-a3fd-41d8c3e7159c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ffc065d-2b72-4514-847f-81306933d5e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ae704cf-5272-4f21-a59b-217d5a1835fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d22fe5c-f8ad-479a-b668-dcc4a4cb4bae</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
