analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:1563961,"name"\:"First Project","teamId"\:1544673,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:1591576,"accountId"\:null,"autoIntegrate"\:false,"sampleProject"\:false}
analytics.team={"id"\:1544673,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
