<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Choose File Branch Information</name>
   <tag></tag>
   <elementGuidId>31214dac-137e-4a9d-8a9d-cd251cc4d0b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:') and contains(@id,'FU_input')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>136b0ebc-30cb-4759-9ab2-41a46453b3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>d9e618c3-c3cb-402a-9a94-fbfd9f7f2a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt449:j_idt449FU_input</value>
      <webElementGuid>a59ad192-904d-4f0f-b869-883f6f5ea20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt449:j_idt449FU_input</value>
      <webElementGuid>7f0d1f37-bf98-4c8d-b570-f780fce89196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please click to upload file(s)</value>
      <webElementGuid>d1385127-5884-4dfd-b739-9d8ab3861e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt449:j_idt449FU_input&quot;)</value>
      <webElementGuid>dab6112d-fc0d-4e72-868a-23f07343d649</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt449:j_idt449FU_input']</value>
      <webElementGuid>5f6883a8-c632-4ad8-9504-ef0efa826ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt449:j_idt449FU']/div/label/input</value>
      <webElementGuid>284f5e95-a854-4713-b7da-bb76d99d5119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>144d5179-fa96-4315-89d3-f4c20f34ac47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = '_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt449:j_idt449FU_input' and @name = '_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt449:j_idt449FU_input' and @title = 'Please click to upload file(s)']</value>
      <webElementGuid>58a49483-9c86-43ca-b49b-f09b104580ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
