<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Telephone No</name>
   <tag></tag>
   <elementGuidId>96c2d728-619a-420c-80ec-6b3f5914e1c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:phoneNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>459ead84-420d-4a1c-b541-aa604d6264cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:phoneNo</value>
      <webElementGuid>683d182f-67f1-4cd1-b3da-7daf74b21777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:phoneNo</value>
      <webElementGuid>751714b5-d700-4bec-b32b-09cea8a4cbd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e1a6293-84d8-4e09-92c4-fe1a1944f72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>514a50fb-fe08-412f-9fcc-421538e91b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>d63cbc55-10a8-4bc3-bc6e-ce2d1e6e042e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover</value>
      <webElementGuid>0a4bd265-93b3-40d3-9e7b-02e1a50a5b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>02976788-fe6e-4a2c-855a-503c5c1cfb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>24bdc4c3-13b6-47b8-b936-873345266c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f6c9c00f-50e2-46b0-80a5-000f91eda327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>96f660df-563c-4910-b727-b566d1f1094f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>08e7ba95-65be-440e-9e2d-7f73ecb68431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:phoneNo&quot;)</value>
      <webElementGuid>fc1861df-1a16-4ee7-b78d-cf6ddc3b5ba1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:phoneNo']</value>
      <webElementGuid>f0e7fd6f-8a7a-4221-8d89-9f6421963a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt281_content']/table/tbody/tr[4]/td[4]/input</value>
      <webElementGuid>3d5651eb-92de-4327-9fcd-3a8dc8050ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>967e4ba4-7d48-4c53-b9d5-d14b1b769ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:phoneNo' and @name = '_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:phoneNo' and @type = 'text']</value>
      <webElementGuid>99e959fc-304a-4e5a-a731-e7a16e3bf7b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
