<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click Assign Button Service</name>
   <tag></tag>
   <elementGuidId>e45ac55d-bee1-4206-9732-26c2af72585d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,':spg_header') and .//span[normalize-space(.)='Service']]&#xd;
/following-sibling::*[1]&#xd;
//button[contains(@id,':questionTbl:0:')]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>019d168b-760d-4eff-9cba-1e53525ced74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>9da2febc-9ece-4931-9365-ccdab531cde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assign</value>
      <webElementGuid>09143dcc-b158-4b82-81b8-e6ae48d658be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt775:questionTbl:0:j_idt872&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>f0935951-e0a6-4a77-a458-bdfd3cc411cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt775:questionTbl:0:j_idt872']/span</value>
      <webElementGuid>92c0fdfc-5d4b-4dc0-8175-b6803e751ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[1]/following::span[3]</value>
      <webElementGuid>fc4c9dab-405d-49a4-9bda-ac14b70337f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service 1'])[1]/following::span[9]</value>
      <webElementGuid>26087eb4-3098-4939-b9a0-5eab29ac37ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ui-button'])[9]/preceding::span[2]</value>
      <webElementGuid>49e14077-83a1-4f81-bcdd-6f94f6ca2de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ui-button'])[10]/preceding::span[4]</value>
      <webElementGuid>f0567ace-bb77-49cf-b5ef-c42a6d56de85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/button/span</value>
      <webElementGuid>f1b4fb40-14f9-4f94-ac32-b612a3cfc3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Assign' or . = 'Assign')]</value>
      <webElementGuid>1590618a-4e54-4620-b4dd-946e17f09795</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
