<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click Sign Out</name>
   <tag></tag>
   <elementGuidId>464b666f-d225-4ecb-a5ac-f094b4fd0afc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[contains(@class,'sign-out')]//span[normalize-space(.)='Sign Out']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yui_patched_v3_11_0_1_1771869191682_503</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>543aa6a0-5330-47eb-9009-2ab76e2311e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://ngepsso.eperolehan.com.my/oam/server/logout?end_url=http://ngepsit.eperolehan.com.my/c/portal/logout</value>
      <webElementGuid>13446094-cfb8-4367-ac82-bb54f68a8445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_patched_v3_11_0_1_1771869191682_503</value>
      <webElementGuid>e6246270-576f-4147-a24c-86ed76201b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>c930110c-013c-47b8-b96e-98790da5ef44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7843a1aa-2231-4fab-8dfe-1b3b83a1d175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   Sign Out  </value>
      <webElementGuid>7541a57b-c34a-4fd6-a3d6-f2b2928262b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_patched_v3_11_0_1_1771869191682_503&quot;)</value>
      <webElementGuid>5de89880-dd40-4ce2-9add-60fd7b0f31fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='yui_patched_v3_11_0_1_1771869191682_503']</value>
      <webElementGuid>5969a0c8-7e32-4e59-9a8b-0133d62786f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='chdz_']/a</value>
      <webElementGuid>88b577d5-95b5-4ddb-8cea-380e591d85f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[1]/following::a[1]</value>
      <webElementGuid>f6c5733f-a5d0-45e5-b287-c6133436fddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khairulakilah Binti Megat Sharuddin'])[1]/following::a[2]</value>
      <webElementGuid>14c44458-4adb-4259-a5ec-c6a36f6896fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/preceding::a[2]</value>
      <webElementGuid>20d122f3-4543-4802-bfc5-17a82bcd597d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://ngepsso.eperolehan.com.my/oam/server/logout?end_url=http://ngepsit.eperolehan.com.my/c/portal/logout']</value>
      <webElementGuid>97adb85e-a617-494e-ae49-a24298890f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/ul/li[2]/a</value>
      <webElementGuid>c2a749df-0644-471a-99e3-c707d6f47409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://ngepsso.eperolehan.com.my/oam/server/logout?end_url=http://ngepsit.eperolehan.com.my/c/portal/logout' and @id = 'yui_patched_v3_11_0_1_1771869191682_503' and (text() = '   Sign Out  ' or . = '   Sign Out  ')]</value>
      <webElementGuid>8c3147dd-5bd2-4be1-bce7-478024ac600f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
