<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Zone Name</name>
   <tag></tag>
   <elementGuidId>e861c168-522f-438e-bfb1-9609d5356584</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_scReviewManualSourcing_WAR_NGePportlet_:form:zoneNameId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e950af7-e026-478b-9428-2a4ce4b0d951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_scReviewManualSourcing_WAR_NGePportlet_:form:zoneNameId</value>
      <webElementGuid>b2fb1364-8d06-495b-a2d8-4575d2c73d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_scReviewManualSourcing_WAR_NGePportlet_:form:zoneNameId</value>
      <webElementGuid>0de83e05-9a78-4d3f-be70-783f98dd6984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a11aff3f-c325-4c06-9e25-5a74169a649c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>7259cee2-37bd-472b-b22c-02884ddec018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>a5b3a689-dd3b-4e43-975a-12bfe66f39f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-error ui-state-hover ui-state-focus focus</value>
      <webElementGuid>1a6f8f3a-8896-4dd0-b95c-0791fd1eb7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>31e49f12-1d30-4a9a-a785-d8412eb99fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6e7ebc92-4573-4cc6-9282-2ab379683ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6f90727f-aed6-4547-8aa8-51d0e1637f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ea84e3d4-0cbb-4179-bf89-0beb7606323d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scReviewManualSourcing_WAR_NGePportlet_:form:zoneNameId&quot;)</value>
      <webElementGuid>8a05cec9-dfe7-41c9-86e1-80dd3d484103</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_scReviewManualSourcing_WAR_NGePportlet_:form:zoneNameId']</value>
      <webElementGuid>d999ce8d-7eeb-40d8-8465-411e47dec1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_scReviewManualSourcing_WAR_NGePportlet_:form:zonePopupGeneral']/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>0d76b97b-c81c-4a40-bdf2-a8f33e802152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>80309c06-a79f-4554-9c8b-52c1cf7dafd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_scReviewManualSourcing_WAR_NGePportlet_:form:zoneNameId' and @name = '_scReviewManualSourcing_WAR_NGePportlet_:form:zoneNameId' and @type = 'text']</value>
      <webElementGuid>d4ccfe7a-b20f-450e-b672-5a3c3e79573e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
