<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Justification</name>
   <tag></tag>
   <elementGuidId>c5abe7ec-c0af-4d28-b80d-b6db4b9f333c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;_Catalogue_WAR_NGePportlet_:form:justificationRmkRPT&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>10824e7e-949d-41d2-b7bd-7bf48474a00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_Catalogue_WAR_NGePportlet_:form:justificationRmk</value>
      <webElementGuid>42236527-6b5e-4e2e-b784-37369cdf0ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_Catalogue_WAR_NGePportlet_:form:justificationRmk</value>
      <webElementGuid>6206638c-72e6-40d8-a303-445b0e6d2cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>58</value>
      <webElementGuid>5fbe11d5-d612-4462-9fda-aac33be29620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>0ced6991-e43e-4a2a-97e5-862e8d208264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>limitTextArea(this,100);</value>
      <webElementGuid>933a650d-647b-4d4f-b8bf-7bda9639dbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>limitTextArea(this,100);</value>
      <webElementGuid>3db1f72e-50eb-4ef8-9bd7-b22538673e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>limitTextArea(this,100);</value>
      <webElementGuid>a59fbd4b-5a34-4e7c-a463-65d2ac77539b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtextarea ui-widget ui-state-default ui-corner-all ui-inputtextarea-resizable ui-state-hover ui-state-focus focus</value>
      <webElementGuid>19f1eb9e-fdb6-4e5d-9ff1-6065cbd5e4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>688de8a7-f10b-489d-a32f-0d0f8e5d5007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e9e13eae-6edc-464e-be59-d60133d1c4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7e1dc1ba-ff77-4a0d-94df-1e893e8fe648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>40cd5c51-fbef-42ef-92a2-bee887688e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_Catalogue_WAR_NGePportlet_:form:justificationRmk&quot;)</value>
      <webElementGuid>a50961b3-abb3-4ab1-bb40-9f561a1d522d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='_Catalogue_WAR_NGePportlet_:form:justificationRmk']</value>
      <webElementGuid>a96fabb2-931c-41e9-b641-a14098ee173d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_Catalogue_WAR_NGePportlet_:form:justId']/table/tbody/tr[2]/td[2]/textarea</value>
      <webElementGuid>0c0749c2-87bd-41aa-afa6-bdf26a271b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/textarea</value>
      <webElementGuid>2e1af0c5-7124-4c8a-9a62-719e5574239d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = '_Catalogue_WAR_NGePportlet_:form:justificationRmk' and @name = '_Catalogue_WAR_NGePportlet_:form:justificationRmk']</value>
      <webElementGuid>b8ff2e82-ea31-423f-b29f-f429d44fa464</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
