<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Justification</name>
   <tag></tag>
   <elementGuidId>c5abe7ec-c0af-4d28-b80d-b6db4b9f333c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='_Catalogue_WAR_NGePportlet_:form:justificationRmk']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3f374937-b701-4a50-a2a9-4c8f7ece1a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_Catalogue_WAR_NGePportlet_:form:justificationRmk</value>
      <webElementGuid>d6ae3a41-4959-4da8-942b-456cbec3c6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_Catalogue_WAR_NGePportlet_:form:justificationRmk</value>
      <webElementGuid>7d78aaed-5f52-45cc-93b1-a9f39a1e52b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>58</value>
      <webElementGuid>437039c1-5a12-4d83-8a8b-5df25b31c0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9f020d6f-25f0-41c1-967f-abc14a9cd8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>limitTextArea(this,100);</value>
      <webElementGuid>b69b56e3-862d-43dc-a4bc-83e8ee038fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>limitTextArea(this,100);</value>
      <webElementGuid>7f2aed41-2bb0-4e60-badc-8256bbc6b576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>limitTextArea(this,100);</value>
      <webElementGuid>dfc29506-4a8a-4b17-9be5-b87c18d7d09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtextarea ui-widget ui-state-default ui-corner-all ui-inputtextarea-resizable ui-state-hover ui-state-focus focus</value>
      <webElementGuid>787326ec-6b77-4f1d-8cab-ed96912ac5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>4ba6bb9f-a188-4fa5-abfe-05d1985640c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>55986981-df3c-44a0-8b7b-e092075d4434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>136abd11-a8bf-4c6c-9b14-6071d04f3421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a17ef67a-90f9-4bc4-bb45-d02e3a2eeaf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_Catalogue_WAR_NGePportlet_:form:justificationRmk&quot;)</value>
      <webElementGuid>35130248-e664-4b2a-9559-c361db0454ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='_Catalogue_WAR_NGePportlet_:form:justificationRmk']</value>
      <webElementGuid>41c01498-095a-4d4e-82f3-22a68789e1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_Catalogue_WAR_NGePportlet_:form:justId']/table/tbody/tr[2]/td[2]/textarea</value>
      <webElementGuid>2d357da8-15b1-497d-b243-b3af412c1d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/textarea</value>
      <webElementGuid>eccf5757-0b75-424e-a590-d8259472ca61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = '_Catalogue_WAR_NGePportlet_:form:justificationRmk' and @name = '_Catalogue_WAR_NGePportlet_:form:justificationRmk']</value>
      <webElementGuid>5319594d-3a47-4769-8135-94e4e6d0828c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
