<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Procurement Type Radio Button</name>
   <tag></tag>
   <elementGuidId>b57290d0-4ede-4391-8a5f-ded67e0f72f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='_Catalogue_WAR_NGePportlet_:form:procurementType']/tbody/tr/td[7]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-radiobutton-box.ui-widget.ui-corner-all.ui-state-default.ui-state-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>234d5599-e07e-44e6-9fce-e1cbb5cad3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-radiobutton-box ui-widget ui-corner-all ui-state-default ui-state-hover</value>
      <webElementGuid>d4fce842-a30e-4503-8359-f7f836aabdd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_Catalogue_WAR_NGePportlet_:form:procurementType&quot;)/tbody[1]/tr[1]/td[7]/div[@class=&quot;ui-radiobutton ui-widget&quot;]/div[@class=&quot;ui-radiobutton-box ui-widget ui-corner-all ui-state-default ui-state-hover&quot;]</value>
      <webElementGuid>b117a379-86b1-4690-b589-41be7f68b0ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='_Catalogue_WAR_NGePportlet_:form:procurementType']/tbody/tr/td[7]/div/div[2]</value>
      <webElementGuid>3a7e8c27-2650-4017-9288-9aaff1da8f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='G2G'])[1]/following::div[3]</value>
      <webElementGuid>550abd5b-5221-41ff-a99a-9891f3c316ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ad Hoc'])[1]/following::div[6]</value>
      <webElementGuid>abbcaf7c-905e-449c-a958-6826945c970f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Item / PK7'])[1]/preceding::div[1]</value>
      <webElementGuid>8cbb6bd2-06cc-4e47-b695-9371c57afad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zonal'])[1]/preceding::div[2]</value>
      <webElementGuid>c0e1e3c7-01c4-471a-af95-a276325b529c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/div[2]</value>
      <webElementGuid>a7f8d23f-bacf-44ac-ac46-26dedf566d2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
