<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Start Date Hour</name>
   <tag></tag>
   <elementGuidId>46ff61f4-7459-4448-8055-0ba3f3ecafa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='_Catalogue_WAR_NGePportlet_:form:startDatesb:calHour']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5773290e-fcc1-4496-9862-b3bdbda9ca80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_Catalogue_WAR_NGePportlet_:form:startDatesb:calHour</value>
      <webElementGuid>500fb4aa-7a08-4fff-bb29-d8bba2779b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_Catalogue_WAR_NGePportlet_:form:startDatesb:calHour</value>
      <webElementGuid>a136b85d-a5bf-41b1-9328-c8e523578af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>62dd40bd-4c1b-4383-aba7-0c3613b891ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({source:this,event:'change',process:'_Catalogue_WAR_NGePportlet_:form:startDatesb:calHour',update:'_Catalogue_WAR_NGePportlet_:form:startDatesb:calHour',partialSubmit:true,oncomplete:function(xhr,status,args){startDate0SetValue();;}}, arguments[1]);</value>
      <webElementGuid>82a70770-bbc7-47bb-8d6f-0c828aaf9e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>	Hour
	00
	01
	02
	03
	04
	05
	06
	07
	08
	09
	10
	11
	12
	13
	14
	15
	16
	17
	18
	19
	20
	21
	22
	23
</value>
      <webElementGuid>b2ba0b08-5129-46bd-840f-69430e0de033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_Catalogue_WAR_NGePportlet_:form:startDatesb:calHour&quot;)</value>
      <webElementGuid>7a138a6e-92d6-42aa-b036-7c42fa78e4e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='_Catalogue_WAR_NGePportlet_:form:startDatesb:calHour']</value>
      <webElementGuid>138b92f0-c908-4488-a9b8-1eaea79e4e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_Catalogue_WAR_NGePportlet_:form:startDatesb:startDate']/select</value>
      <webElementGuid>d960720a-1929-4c26-9d8e-f080dc4aa87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ui-button'])[2]/following::select[1]</value>
      <webElementGuid>561bf733-1f9b-4b66-aa35-9922a6677473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>7f0b480a-0f5c-4466-b60b-65e6a0769bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[1]/preceding::select[2]</value>
      <webElementGuid>38d65610-076e-48fc-84dd-fceccc20423f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::select[2]</value>
      <webElementGuid>5f8c23a2-6b76-4856-abaf-a2ffea4bd269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/select</value>
      <webElementGuid>1ebcf20d-779c-4f6c-9170-9622512f1175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '_Catalogue_WAR_NGePportlet_:form:startDatesb:calHour' and @name = '_Catalogue_WAR_NGePportlet_:form:startDatesb:calHour' and (text() = '	Hour
	00
	01
	02
	03
	04
	05
	06
	07
	08
	09
	10
	11
	12
	13
	14
	15
	16
	17
	18
	19
	20
	21
	22
	23
' or . = '	Hour
	00
	01
	02
	03
	04
	05
	06
	07
	08
	09
	10
	11
	12
	13
	14
	15
	16
	17
	18
	19
	20
	21
	22
	23
')]</value>
      <webElementGuid>aaeb6da8-b361-4d1e-9327-84d9fb161409</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
