<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Quantity</name>
   <tag></tag>
   <elementGuidId>8ac61e48-4b0f-4687-9d43-fd62b9df5c11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,':spg_header') and .//span[normalize-space(.)='Service']]&#xd;
/following-sibling::*[1]&#xd;
//input[contains(@id,':questionTbl:') and substring(@id, string-length(@id) - string-length(':qty') + 1) = ':qty']&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06d13c1e-2c32-410d-a0ce-e7135b9afede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:0:qty</value>
      <webElementGuid>699d6d18-9cec-45d3-98e6-ac6acf977827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:0:qty</value>
      <webElementGuid>47a6fc6e-0704-4878-b995-849aae89b00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5cba0820-6335-4c66-978f-a416b7b4d065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>9c48f761-4dad-4fad-9c5d-10c4bce7073c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover</value>
      <webElementGuid>1d7b62b4-d607-49e8-aab9-0bdc7303a186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>0e3414e1-e14d-4fca-ab19-e325c964a008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>efc474ea-606a-4578-a043-65095afad3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9143a94d-2ebe-4e17-bd89-a55738377d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9009e41f-c717-4ee6-9238-76a230eadd3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:0:qty&quot;)</value>
      <webElementGuid>cc7d6967-84d8-4601-b36b-eff7ec47b638</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:0:qty']</value>
      <webElementGuid>aae9793a-28a6-4c1c-b154-d10e212662bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:0:qtyPG']/input</value>
      <webElementGuid>fd15cec0-e73b-4399-b4d1-dba9a6539296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/span/input</value>
      <webElementGuid>0d2d8adc-521b-4168-b339-259126ae9573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:0:qty' and @name = '_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:0:qty' and @type = 'text']</value>
      <webElementGuid>bd94a187-efd8-4841-a1d9-d7dfc0ce0d8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
