<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Purchase Number</name>
   <tag></tag>
   <elementGuidId>2937cb3e-33ae-4a06-bd24-6e1e98f69a85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[contains(@name,'flPendingDeliveryList') and @type='text'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49019d52-1150-4656-8333-58ed80e82e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_BpmTaskList_WAR_NGePportlet_:form:j_idt130</value>
      <webElementGuid>83043c73-4b19-4d5e-b5bc-46e05b09591b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_BpmTaskList_WAR_NGePportlet_:form:j_idt130</value>
      <webElementGuid>bed52894-d07f-4867-8ace-e0929cf9d984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04d830c7-067a-4430-bf9e-df4eb2430eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>8cf5a0d6-42a7-49d0-92c2-a06e64e678a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus focus</value>
      <webElementGuid>150109c8-b73a-4041-9955-d614bc8573f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a54e262a-30fd-433e-ba8e-f80e7e9dc488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>909d05a2-fa42-43eb-afc3-5fe9153429b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1e843523-1469-4155-afb6-47f3954ed0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>00c9a62b-443c-4e91-97e3-af2bf302f126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fbb3707d-d20b-4a9d-9db4-5aa6cec8f4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_BpmTaskList_WAR_NGePportlet_:form:j_idt130&quot;)</value>
      <webElementGuid>27142ba9-91a7-484b-877e-45b5964a7225</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_BpmTaskList_WAR_NGePportlet_:form:j_idt130']</value>
      <webElementGuid>fea3ce18-4df9-4ce6-b871-63ec45e17479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_BpmTaskList_WAR_NGePportlet_:form:normalViewPanelId_content']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>5033f78b-451a-4432-a6f2-eba2d00d8326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>526ee632-a29c-4182-9380-da153f6d1b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_BpmTaskList_WAR_NGePportlet_:form:j_idt130' and @name = '_BpmTaskList_WAR_NGePportlet_:form:j_idt130' and @type = 'text']</value>
      <webElementGuid>292343a9-c712-4e39-9329-b7f84ae89645</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
