<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input UOM</name>
   <tag></tag>
   <elementGuidId>2b6c8a32-0ff0-4a54-b238-25c2b164da66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,':spg_header') and .//span[normalize-space(.)='Service List']]&#xd;
/following-sibling::*[1]&#xd;
//input[contains(@id,':questionTbl:') and substring(@id, string-length(@id) - string-length(':uom_input') + 1) = ':uom_input']&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7926103-4962-45f9-94d6-c4ada97497f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:0:uom_input</value>
      <webElementGuid>55ae5cf9-26d9-44e3-a35a-1d5b48f7d4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:0:uom_input</value>
      <webElementGuid>8521c9f2-8e44-4d50-bccf-0138f4eaf2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9cde3ef7-b6c4-458a-9280-df404dd6bf57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-input ui-inputfield ui-widget ui-state-default ui-corner-all ui-state-hover</value>
      <webElementGuid>39738f6a-4134-4dbd-a8ba-43b8bc4571d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b2bbdee8-5f9a-47a1-b2fb-a36c7a571f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>38e9d31d-3b17-4238-b441-da916339ad04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>f23aeff3-7fdc-44cb-8614-0fdba45e997d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e8fd7c47-a978-437d-b0d2-0524ffb61885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a8cc9549-0b6b-4133-9b13-280c7557fce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6984b7d3-faf1-46a4-9754-157d3c2f538e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:0:uom_input&quot;)</value>
      <webElementGuid>3096a069-2823-479e-b0e6-5e269946fea9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:0:uom_input']</value>
      <webElementGuid>b6ab6ece-838f-43a7-b092-483111e05557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:0:uom']/input</value>
      <webElementGuid>8a5613b2-350c-478e-8516-a349d4c14676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/table/tbody/tr/td[2]/div/span/input</value>
      <webElementGuid>43e06758-7afa-46d9-b919-7491f73202fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:0:uom_input' and @name = '_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:0:uom_input' and @type = 'text']</value>
      <webElementGuid>ac714920-e983-4886-b05a-da44bf869114</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
