<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Specification 2 TextBox</name>
   <tag></tag>
   <elementGuidId>73a0e382-7431-48eb-bf6b-02ad22c2f7d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,':spg_header') and .//span[normalize-space(.)='Service List']]&#xd;
/following-sibling::*[1]&#xd;
//textarea[contains(@id,':questionTbl:') and substring(@id, string-length(@id) - string-length(':specification') + 1) = ':specification']&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b36cf896-d668-4580-aa9f-c4a3c05e0883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:1:specification</value>
      <webElementGuid>a589e00b-ab1f-4951-9638-17c667102acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:1:specification</value>
      <webElementGuid>b53b9f91-7e3e-4d2d-9901-bf043cb8b70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>c89cdca7-8a31-4bcd-9727-7aa6b3f84242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>88f6881b-8b32-4866-93a9-ea184102e7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>limitTextAreaWithBreakline(this,1000);</value>
      <webElementGuid>7428140a-0b3a-4fd0-a945-cc43eef4a5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>limitTextAreaWithBreakline(this,1000);</value>
      <webElementGuid>2e4d707e-6f6b-47f6-8356-6684221f5daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>limitTextAreaWithBreakline(this,1000);</value>
      <webElementGuid>4c038880-bc3f-484d-81c1-203a05b73a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtextarea ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus focus</value>
      <webElementGuid>25c8ba78-6c46-48d9-a2ee-c0a800e263d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>f331b81b-b052-40e3-9765-ce202e79f5f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f6ed4db8-cfdc-4491-9b8b-0259ed069b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9a055755-3b42-40eb-9d7b-b6ba05c7c3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>271de5ec-dde8-431c-b93d-5638d79f59da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:1:specification&quot;)</value>
      <webElementGuid>c5e82a3c-d889-45d7-ad4f-080188aec1d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:1:specification']</value>
      <webElementGuid>2d2ceb44-3f2b-4df8-8c56-f379f623eb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl_data']/tr[2]/td/textarea</value>
      <webElementGuid>10d21e0c-f3e0-4870-a29b-981d3f89a3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/table/tbody/tr[2]/td/textarea</value>
      <webElementGuid>d9ea180d-6950-4684-b766-84dd59b2cc16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = '_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:1:specification' and @name = '_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1108:questionTbl:1:specification']</value>
      <webElementGuid>180bc48d-f1fe-4107-a0a2-efa26a8261df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
