<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Service Input Specification 1 TextBox</name>
   <tag></tag>
   <elementGuidId>13884e9e-c51f-43e0-a8e3-7771c54f56a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,':spg_header') and .//span[normalize-space(.)='Service List']]&#xd;
/following-sibling::*[1]&#xd;
//textarea[contains(@id,':questionTbl:') and substring(@id, string-length(@id) - string-length(':itemName') + 1) = ':itemName']&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>14b6475e-734b-4663-a968-d6b917f15679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1011:questionTbl:0:itemName</value>
      <webElementGuid>cc49c420-5b4a-45ae-867e-7ab6bde70433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1011:questionTbl:0:itemName</value>
      <webElementGuid>1655c6b7-4417-44db-ae8a-22eeb4f22843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>1f8bab1a-2d69-4a05-a15e-f813c6576b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>4bbc57ae-b851-4a14-bdcd-a57788ca6dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>limitTextArea(this,2000);</value>
      <webElementGuid>51a46517-1f13-4160-9be1-0ea57b4ee758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>limitTextArea(this,2000);</value>
      <webElementGuid>6f0b8e20-1afb-4246-a85b-f448f14cef09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>limitTextArea(this,2000);</value>
      <webElementGuid>5c436219-39f4-4ca4-87a4-efb21b6fb9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtextarea ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus focus</value>
      <webElementGuid>e9c6e406-0ad3-4888-9a2c-b42ad958679a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>13d44826-dd8a-42ee-b81a-b92a7259b465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b7810a31-ce3e-4b11-9362-3bab444a43fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>752181f7-b946-471b-821c-68c0213c6e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8d583cff-23c8-4c99-a631-d8a3fc40295f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1011:questionTbl:0:itemName&quot;)</value>
      <webElementGuid>bbbe7d1d-fa7e-4f61-9983-0e17809cde9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1011:questionTbl:0:itemName']</value>
      <webElementGuid>60712d98-610c-4812-9294-ccbad31b3c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1011:questionTbl_data']/tr/td/textarea</value>
      <webElementGuid>640e53eb-56b6-4f3b-bfeb-77d93b242cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>667b92b4-9484-4945-8336-cbdf62931c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = '_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1011:questionTbl:0:itemName' and @name = '_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1011:questionTbl:0:itemName']</value>
      <webElementGuid>4a900801-f874-462c-8515-dff1d8c33afa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
