<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown Measurement</name>
   <tag></tag>
   <elementGuidId>279316a1-7fd1-4273-acd3-69bde3b38d6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[normalize-space()='Measurement']/following::div[contains(@class,'ui-selectonemenu')][1]/div[3]&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aa8fce7d-1581-4fef-a80d-4f1b0101f988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-trigger ui-state-default ui-corner-right</value>
      <webElementGuid>4ea4b379-1954-4c8f-ba2c-752534ae297f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt76&quot;)/div[@class=&quot;ui-selectonemenu-trigger ui-state-default ui-corner-right&quot;]</value>
      <webElementGuid>62aa2dfd-ae50-4173-9468-97df8fe6660b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt76']/div[3]</value>
      <webElementGuid>1496a300-269f-4e32-9a4e-d223b7f0c3f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Select One -'])[6]/following::div[1]</value>
      <webElementGuid>2797b140-8884-48a8-91b6-7c79ff4623dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Measurement'])[1]/following::div[4]</value>
      <webElementGuid>653c4f78-2952-42f7-916b-b73c0bfd6f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/preceding::div[1]</value>
      <webElementGuid>0f9939d8-ce99-48b7-9d34-884e4876b8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Select One -'])[8]/preceding::div[3]</value>
      <webElementGuid>7cb79bec-8d27-422d-9b10-f9eed8807d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/div/div[3]</value>
      <webElementGuid>29705753-faad-4513-83a2-75c2d9a8e900</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
