<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown Language</name>
   <tag></tag>
   <elementGuidId>d3aee502-4c86-4a56-a0f0-b46ad896e6af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='_82_languageId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_82_languageId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>18e13503-0b6b-4be4-96f7-049aaa22b26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aui-field-select</value>
      <webElementGuid>4f38ee35-e1da-4077-b145-c12a0fe6ca0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_82_languageId</value>
      <webElementGuid>b1c924a7-a7e7-43b2-a2a0-46d90461fa7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_82_languageId</value>
      <webElementGuid>074ecd07-2df8-4af9-a2c2-f9cbe8f6feab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>submitForm(document._82_fm);</value>
      <webElementGuid>dd44bb06-496a-4bb9-b2da-5aa5ebf4fea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Bahasa (Changing the value of this field will reload the page.)</value>
      <webElementGuid>70a728fe-e021-4da0-81c7-89dd5e598373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Bahasa Melayu   English  </value>
      <webElementGuid>604e1059-3d3b-48be-bf2c-359c2f6853d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_82_languageId&quot;)</value>
      <webElementGuid>647c6fff-a260-4b9e-af97-50587baf25ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='_82_languageId']</value>
      <webElementGuid>0d997666-9887-49c3-aad6-2ad6da7cfac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='_82_fm']/div/select</value>
      <webElementGuid>0fab4c1c-961d-4074-85e8-c640b9f45389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimize'])[4]/following::select[1]</value>
      <webElementGuid>2f0ec501-df42-45d1-bba4-1ff1fd3474e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximize'])[4]/following::select[1]</value>
      <webElementGuid>acfdcb53-63ec-4e4c-8d71-140ba91dddb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengumuman'])[1]/preceding::select[1]</value>
      <webElementGuid>585963cf-ccff-4a69-9ed1-420996fc9f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengumuman Cuti Bagi Pegawai Kementerian Kewangan'])[1]/preceding::select[1]</value>
      <webElementGuid>fda80261-2154-499d-8a80-13aaeb339e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>26933d36-449a-4173-bea0-951447098641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '_82_languageId' and @name = '_82_languageId' and @title = 'Bahasa (Changing the value of this field will reload the page.)' and (text() = '  Bahasa Melayu   English  ' or . = '  Bahasa Melayu   English  ')]</value>
      <webElementGuid>474b481d-d7b9-4acf-9ad9-5f326b90917c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1770087337034_442']/select</value>
      <webElementGuid>2bda9113-6952-4cd1-955f-e165e84db219</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
