<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button LOA Signer</name>
   <tag></tag>
   <elementGuidId>d4ccd0e4-a853-462c-85e1-93a0bc5dc60c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@id,'lovUserlovLink')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f56101fd-41a5-4e56-a006-142838c009b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_scCreateManualSourcing_WAR_NGePportlet_:form:lovUser:j_idt722</value>
      <webElementGuid>9199626b-5d1f-4078-b43e-e83f34880ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/NGeP-portlet/css/images/design/search.png</value>
      <webElementGuid>619552e8-caeb-4294-bfa1-d74be01981f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scCreateManualSourcing_WAR_NGePportlet_:form:lovUser:j_idt722&quot;)</value>
      <webElementGuid>d96695fd-9006-43d7-bb32-bfbe272773b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='_scCreateManualSourcing_WAR_NGePportlet_:form:lovUser:j_idt722']</value>
      <webElementGuid>314450f6-bad8-4e35-9008-7e79051c3d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='_scCreateManualSourcing_WAR_NGePportlet_:form:lovUser:lovUserlovLink']/img</value>
      <webElementGuid>8efe7995-51e4-4e36-96da-11e6197df9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a/img</value>
      <webElementGuid>e09444c0-6be5-472b-b22c-43f2b26ac85f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '_scCreateManualSourcing_WAR_NGePportlet_:form:lovUser:j_idt722' and @src = '/NGeP-portlet/css/images/design/search.png']</value>
      <webElementGuid>8fd075b9-58ef-4fc9-bf42-7d20b70710e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
