<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create LOA</name>
   <tag></tag>
   <elementGuidId>7cb03d9e-c52a-450d-b212-7b50a4860ceb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[normalize-space()='Create LOA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>09a2949c-ceef-4333-b9cd-2075afbd2087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menuItemLink</value>
      <webElementGuid>5b4ac42d-fc53-4160-bbf2-91dabe301f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/web/epapp/create-manual-sourcing</value>
      <webElementGuid>e1079a3e-abf0-406e-910b-98cfc75bc705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create LOA</value>
      <webElementGuid>c6d51e67-9326-464b-9dc1-10d92bd45a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quicklink&quot;)/div[@class=&quot;mainparent grid&quot;]/div[@class=&quot;layoutitem grid-item&quot;]/ul[@class=&quot;subparent&quot;]/li[@class=&quot;layoutsubitem&quot;]/div[2]/a[@class=&quot;menuItemLink&quot;]</value>
      <webElementGuid>cf2891f7-1784-4f61-953a-4d9a76e6c13b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quicklink']/div/div/ul/li[4]/div[2]/a</value>
      <webElementGuid>9c156f91-c56c-47f4-839f-67fba88fa024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create LOA')]</value>
      <webElementGuid>567c51a1-f3fa-49f6-8844-4938b53aa67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bidding Management'])[1]/following::a[1]</value>
      <webElementGuid>35b75df3-2305-4d71-b46b-fd94798680cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quotation/Tender Maintenance'])[1]/following::a[2]</value>
      <webElementGuid>8acdd05b-e4f0-4768-9cd5-eb98bc10d38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Of Supplier Based On Criteria'])[1]/preceding::a[1]</value>
      <webElementGuid>7db1b6d9-a96a-4a85-bd7e-2f76f3899cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Market Research'])[1]/preceding::a[2]</value>
      <webElementGuid>975370b8-2529-43fa-b52b-1e2709d5f161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create LOA']/parent::*</value>
      <webElementGuid>331574b3-c1d4-4360-8fa4-44d52cee3497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/web/epapp/create-manual-sourcing')]</value>
      <webElementGuid>66ef550a-47b9-44d7-81aa-30e22197b1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div[2]/a</value>
      <webElementGuid>51fb13e6-de53-4d00-ae9f-0bab2c8a4b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/web/epapp/create-manual-sourcing' and (text() = 'Create LOA' or . = 'Create LOA')]</value>
      <webElementGuid>51482973-8bf0-4023-afe4-e1d1d0b0897d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
