<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save LOA Application</name>
   <tag></tag>
   <elementGuidId>a4b9f09e-5f89-4d60-b8c2-2bd48b9f228f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ui-button-text.ui-c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[.//span[normalize-space()='Accept']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9d3a3fd9-e31a-4614-acbe-346f44b8a6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>2ca638bd-5349-48be-a58b-026e35d07604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>ce9b0903-aad6-4461-b5ed-8ee9e726a3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt12&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>237c8045-f31b-4f60-a023-a7925a135229</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt12']/span</value>
      <webElementGuid>2756c495-21dd-4439-8768-61442dc98d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimize'])[1]/following::span[2]</value>
      <webElementGuid>ff1f225b-cc01-4e59-a2da-aed13737f74f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximize'])[1]/following::span[4]</value>
      <webElementGuid>bfa373bf-327b-4df3-aae8-1f52fade7635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::span[1]</value>
      <webElementGuid>13c5fa6e-53af-4d29-9b09-d25bdfdd868c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[2]</value>
      <webElementGuid>02996956-efbf-4f01-a6dd-43cfd0cb8654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>98d66764-0e51-46b9-9961-47691717d6da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>9427f7fd-3821-4c91-a9d0-1db2875ee5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>eb410420-e89e-418a-b46f-f1f2b8598928</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
