<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Choose File Branch Information</name>
   <tag></tag>
   <elementGuidId>31214dac-137e-4a9d-8a9d-cd251cc4d0b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='file' and starts-with(@id,'_scLoaSupplierResponse_WAR_NGePportlet_:form:') and contains(@id,'FU_input')]&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6b90948-3489-484c-881c-5f7b31585d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>31002288-a24a-48ef-ac8a-cd7b03f1a5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt449:j_idt449FU_input</value>
      <webElementGuid>e1a53687-f8ef-4dfd-b133-1350ccffcb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt449:j_idt449FU_input</value>
      <webElementGuid>4ee080f5-1c12-4e46-8aa0-032d3fc2b979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please click to upload file(s)</value>
      <webElementGuid>2ef2e337-10e3-424e-b38d-e3759aa94d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt449:j_idt449FU_input&quot;)</value>
      <webElementGuid>54db55dc-9502-48d6-84ef-6f57cd2336ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt449:j_idt449FU_input']</value>
      <webElementGuid>b183f9e5-0c81-440e-be27-c890d8965e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt449:j_idt449FU']/div/label/input</value>
      <webElementGuid>3290f494-5492-4229-8fe7-5d6b7a6809aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>76985c1d-6e70-4b9b-87c0-5f261e3ba2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = '_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt449:j_idt449FU_input' and @name = '_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt449:j_idt449FU_input' and @title = 'Please click to upload file(s)']</value>
      <webElementGuid>39b47320-2fc2-4c8c-b0ec-6ecf9201ee73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
