<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Designation</name>
   <tag></tag>
   <elementGuidId>1bc3f992-2425-40fc-9eab-b80b1e901e62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;_scLoaSupplierResponse_WAR_NGePportlet_:form:designation&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a196728-4bc6-46bf-8d56-41aa33c7f97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:designation</value>
      <webElementGuid>efa94459-0a50-4dad-b94d-8d57249349c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:designation</value>
      <webElementGuid>53069332-8258-478b-acd0-c2bfe11a2fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9578b73-10e8-43ca-8047-d5eb6dc57711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>9f181333-2abd-4dc5-9219-21764cdf3479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>aeed4e6f-ca39-403c-b000-b0883df34581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover</value>
      <webElementGuid>494b6809-b006-4ed8-be57-312d543defcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>958b8d38-4904-4031-a084-fc042c2aa75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>13468976-6f16-45c7-a2d0-7cf3ef8ac1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>943c4ae7-58ed-49e8-902e-61cd0765fb3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3acbb034-8c0b-45ff-b9d7-c9a0c23391c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>07e2cfc6-734a-446a-9ad7-09562a1a88f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:designation&quot;)</value>
      <webElementGuid>f742fe3e-c59d-484e-bcb0-bf8fdd1957d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:designation']</value>
      <webElementGuid>6b8daf57-8171-48c8-a9ba-0781e089b81b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt281_content']/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>f3119045-9f86-44ed-b366-daf0d2152dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>bac77293-b0a8-417a-99ef-b804dce335e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:designation' and @name = '_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:designation' and @type = 'text']</value>
      <webElementGuid>27d1edf6-cb8a-46da-989a-a24980bd2f64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
