<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Identification No</name>
   <tag></tag>
   <elementGuidId>95b4d5dc-983c-429d-b7fa-232b989e13e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;_scLoaSupplierResponse_WAR_NGePportlet_:form:identificationNo&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19ce338d-1a50-4130-b58c-3a393040c455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:identificationNo</value>
      <webElementGuid>8226b68c-ce4c-4aec-87bd-d369bc90258b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:identificationNo</value>
      <webElementGuid>f6e29d4b-a3ea-4287-b4ac-5c1abea5cdee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ebea7c5-e964-4a9a-86b4-f8d105317c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>e98e5efb-5152-41dd-aae5-7f4c2473e5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>bae11e8c-14be-4a82-ae65-599e5548ab6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover</value>
      <webElementGuid>f6b99ae1-0d1c-4313-baa4-80f839cf767d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>52866a69-059e-44ec-972d-d967ec265946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>78cf538a-bc6b-40b8-8fc6-7cd699b2daee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>81c45e20-d4b6-4f11-8303-6c417fc8a9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fb4c7a64-a057-469f-906b-b536591a9903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8832f1ba-287a-4349-9daf-d87ee5555e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:identificationNo&quot;)</value>
      <webElementGuid>7bc06d23-4956-4f66-abad-d13b418381a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:identificationNo']</value>
      <webElementGuid>3267882e-4fb8-4387-97e8-7be5beb08695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:j_idt281_content']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>a8abe85a-53cf-4bf7-be81-ab2028c0059d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>d4ee101d-f328-4002-996c-650beb7651ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:identificationNo' and @name = '_scManualSourcingSupplierResponse_WAR_NGePportlet_:form:identificationNo' and @type = 'text']</value>
      <webElementGuid>b78da949-2ede-40ab-b851-be9322c4df7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
