<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Specification 2 TextBox</name>
   <tag></tag>
   <elementGuidId>511337ac-fd3f-4f65-9202-0334f21c174c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,':spg_header') and .//span[normalize-space()='Service List']]&#xd;
/ancestor::div[1]//textarea[contains(@id,':questionTbl:') and contains(@id,':specification')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>89f3f983-7a2e-4ddb-8513-6995b28b0e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1011:questionTbl:1:specification</value>
      <webElementGuid>935941a5-67a9-4683-8dd2-1b23a07a44d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1011:questionTbl:1:specification</value>
      <webElementGuid>0e52d08c-5a8e-45b7-80c4-b3bc28d54fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>09c39834-e347-4478-8903-0179dcac456e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1e1391d4-d90f-4515-9a32-0ce82e48e420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>limitTextAreaWithBreakline(this,1000);</value>
      <webElementGuid>41276393-f15b-41e0-86e2-d41ec4f57845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>limitTextAreaWithBreakline(this,1000);</value>
      <webElementGuid>2b2978ce-a0f4-4742-b109-11b1b9a77c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>limitTextAreaWithBreakline(this,1000);</value>
      <webElementGuid>2bcbae38-0d05-40cc-a8ca-fb90937b2b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtextarea ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus focus</value>
      <webElementGuid>e127b04e-5dda-495f-8d7a-f87248057e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>16a00191-5f36-42b6-b40a-c0a86b227290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>07a0fa2b-b02b-42b9-804a-6ba2a95a14e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f6cbb19b-81b7-48a1-b47f-ad02022d5892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d048081d-38a0-465e-903b-0ee0dcd84897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1011:questionTbl:1:specification&quot;)</value>
      <webElementGuid>02b0e377-f104-484e-81d3-34a4761d3e8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1011:questionTbl:1:specification']</value>
      <webElementGuid>11af3bd6-fcff-4f06-a78c-4bc20c2a135b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1011:questionTbl_data']/tr[2]/td/textarea</value>
      <webElementGuid>dbb2a98e-30fb-43d8-a634-1135d3afbb55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/textarea</value>
      <webElementGuid>91bd3d5f-8a4f-4ee4-89c2-2c8b00f9c637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = '_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1011:questionTbl:1:specification' and @name = '_scReviewManualSourcing_WAR_NGePportlet_:form:j_idt1011:questionTbl:1:specification']</value>
      <webElementGuid>c7ec8ede-e486-45e2-b6b1-3059c90048c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
