<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DP -PR - Prepare Request Note One Off</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b44f1bed-860d-4b8f-bb09-5d257e413db8</testSuiteGuid>
   <testCaseLink>
      <guid>2a9ae7bb-2b81-40f9-8f0f-912df5121517</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2. DLOA/DP - PR/3. Prepare Request Note One off</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5175ff99-4eed-4bef-8184-2bc789bea081</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DP -PR/PR Note One Off</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>5175ff99-4eed-4bef-8184-2bc789bea081</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>84f17061-4046-4a2a-8c57-b2e32d123585</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5175ff99-4eed-4bef-8184-2bc789bea081</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>642a28d9-99e7-4eff-a098-a277158353fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5175ff99-4eed-4bef-8184-2bc789bea081</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Document_Number</value>
         <variableId>5dc8eb41-a888-4772-a11b-239cc0ac25f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b45c4e3-a6f2-483f-a3c6-76730f96b34d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35a8a808-536a-4fb7-b0c2-b74d4eed403e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33316c60-41e2-421c-8977-21bb13776d0a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
