<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DP - PR - Submit Code</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>daf762df-ceb6-4ee2-90f1-de18b98fb91f</testSuiteGuid>
   <testCaseLink>
      <guid>1e5605f3-8ca0-4750-8b61-a9ac7c965900</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2. DLOA/DP - PR/6. DP DR - Submit Code One Off</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>42f61643-635c-45aa-89e6-fe532b23fd0c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DP -PR/Submit Code One Off</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>42f61643-635c-45aa-89e6-fe532b23fd0c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>8def1ed9-810d-4441-984a-b3eee8e130dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>42f61643-635c-45aa-89e6-fe532b23fd0c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>18cf941a-614d-4158-8e4d-f9e323093ad7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>42f61643-635c-45aa-89e6-fe532b23fd0c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Document_Number</value>
         <variableId>56ace8d4-6c66-46f6-b2fa-89198ac8710a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cb19378-641d-4b09-93b3-574ed8a1125e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9cafc98-d608-46ac-a8b4-fa559bff55f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9e8213c-246d-43a4-b5a0-ced932799ba5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f8119b1-21d4-4940-aa12-31d089b91d4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86672275-a870-4042-9d68-7d3eb754a315</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
