<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Search Supplier - Direct LOA</name>
   <tag></tag>
   <elementGuidId>33a7d246-c9d3-4bb6-9c82-fe56c0dc16b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[starts-with(@id,'_scCreateManualSourcing_WAR_NGePportlet_:form:supplierId:')]&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0f062883-5cfb-4979-931e-ad4138cbb98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_scCreateManualSourcing_WAR_NGePportlet_:form:supplierId:j_idt133</value>
      <webElementGuid>64824fc8-4ec4-4409-a249-ea764aee1c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/NGeP-portlet/css/images/design/search.png</value>
      <webElementGuid>3df94e44-d950-4a29-831a-5bb716a2936e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scCreateManualSourcing_WAR_NGePportlet_:form:supplierId:j_idt133&quot;)</value>
      <webElementGuid>060e5990-ec79-47c1-a061-e195ec0d3216</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='_scCreateManualSourcing_WAR_NGePportlet_:form:supplierId:j_idt133']</value>
      <webElementGuid>ba1a4272-3de4-4e20-8cee-81a6c219140f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='_scCreateManualSourcing_WAR_NGePportlet_:form:supplierId:supplierIdlovLink']/img</value>
      <webElementGuid>294af67d-31da-4610-b5d6-0f1e634c7981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a/img</value>
      <webElementGuid>3559f9cd-ea2d-493e-b595-504998eda264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '_scCreateManualSourcing_WAR_NGePportlet_:form:supplierId:j_idt133' and @src = '/NGeP-portlet/css/images/design/search.png']</value>
      <webElementGuid>68258254-eedf-4230-8750-6601fb0d8584</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
