<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click the Supplier</name>
   <tag></tag>
   <elementGuidId>c951a0f5-2f26-4539-92c4-6d64c2a6be05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.ui-widget-content.ui-datatable-even.ui-state-hover > td:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[contains(@id,'lovTb_data')]/tr[1]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>33de2f34-d97c-4f11-9679-d007b35d099c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>ee6c7918-c163-4eb2-a00d-e81eae1a4bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						eP-1008I048X
				</value>
      <webElementGuid>1f535a6c-99fe-4635-b2d5-5c6824e8fce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scCreateManualSourcing_WAR_NGePportlet_:form:j_idt77:lovTb_data&quot;)/tr[@class=&quot;ui-widget-content ui-datatable-even ui-state-hover&quot;]/td[2]</value>
      <webElementGuid>19535b89-8160-4ca5-8f73-f328e6b58e56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='_scCreateManualSourcing_WAR_NGePportlet_:form:j_idt77:lovTb_data']/tr/td[2]</value>
      <webElementGuid>c2cb5714-dcf1-42db-9475-e3f8f2cabb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BUMI WARISAN MAJU SDN BHD'])[1]/following::td[1]</value>
      <webElementGuid>798e2379-b4c2-4d32-9143-11bcfe25761e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MOF No.'])[2]/following::td[2]</value>
      <webElementGuid>49d18f95-0df7-4a18-ba95-9cae3f204c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NSA BUMIPUTRA SDN BHD'])[1]/preceding::td[3]</value>
      <webElementGuid>5fe53369-ccfa-497c-82d5-f69d789f700a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eP-1601I004V'])[1]/preceding::td[4]</value>
      <webElementGuid>89eadc88-e445-4ced-988d-7e77e9c60b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='eP-1008I048X']/parent::*</value>
      <webElementGuid>bdcb59ef-9054-42e3-b155-53bf27a8434f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/div/div/table/tbody/tr/td[2]</value>
      <webElementGuid>025dc555-76bb-445c-8b46-92d5b3f9da6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
						eP-1008I048X
				' or . = '
						eP-1008I048X
				')]</value>
      <webElementGuid>34713833-bd9b-454e-bab1-4a654f4acb08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
