<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Key In Business Name</name>
   <tag></tag>
   <elementGuidId>0a50b078-19f5-4bec-b088-f5cef808529a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text' and contains(@id,':form:') and contains(@class,'ui-inputtext')]&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47ba9452-a7e8-4c91-a6ba-a1ab9c83e456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_scCreateManualSourcing_WAR_NGePportlet_:form:j_idt75:j_idt84</value>
      <webElementGuid>10faeb9d-fd0b-47ad-a54e-350bcf471ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_scCreateManualSourcing_WAR_NGePportlet_:form:j_idt75:j_idt84</value>
      <webElementGuid>a87179e3-652f-4a44-8840-8b1b45ce1514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5924764-49f1-4996-a1de-373bacc19bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7a0cb549-0688-4b56-9dda-1bc3af7c5b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (event.keyCode == 13) { lovSearch.jq.click(); return false; }</value>
      <webElementGuid>9c7482f3-5c5d-4191-9d92-58d7505ce140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus focus</value>
      <webElementGuid>80a946f0-bd89-465e-b698-a836f5cef6b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>4ba4d710-cfe7-48b7-8df1-3183cca77094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3edbfc08-528d-45d4-b19b-0e96abb93e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>00ae1488-b362-4775-b077-1b3e36721d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9a00d5ac-022a-44e9-81e8-b1bba7a27173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scCreateManualSourcing_WAR_NGePportlet_:form:j_idt75:j_idt84&quot;)</value>
      <webElementGuid>63a82eb1-54fd-4bad-8107-556790778bf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_scCreateManualSourcing_WAR_NGePportlet_:form:j_idt75:j_idt84']</value>
      <webElementGuid>04cd5bc5-f747-4ed1-9979-98f646dd4201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='_scCreateManualSourcing_WAR_NGePportlet_:form:j_idt75:lovCriteria']/tbody/tr/td[2]/input</value>
      <webElementGuid>ee9b0273-0b29-4831-bb5d-04a9fab8311e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>85a0f044-6b0b-42d2-a449-9d20e5a35c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_scCreateManualSourcing_WAR_NGePportlet_:form:j_idt75:j_idt84' and @name = '_scCreateManualSourcing_WAR_NGePportlet_:form:j_idt75:j_idt84' and @type = 'text']</value>
      <webElementGuid>37723836-32d8-4d8f-b8dd-613362c65386</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
