<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>File Reference No_2</name>
   <tag></tag>
   <elementGuidId>fca76a30-89ac-4ed3-be92-518ae0197dbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_scCreateManualSourcing_WAR_NGePportlet_:form:fileExtNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfbdf8e7-b97e-4981-b4e3-da8d2659d652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_scCreateManualSourcing_WAR_NGePportlet_:form:fileExtNo</value>
      <webElementGuid>792387e0-761c-4249-b014-52f9598a018b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_scCreateManualSourcing_WAR_NGePportlet_:form:fileExtNo</value>
      <webElementGuid>af405c82-29f3-4f17-85d2-1b8cb453162a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ac768a45-6892-400c-9748-570962de4079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8abd5374-1244-45cb-8dab-5bcd633874fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>73a3e38b-dddd-460a-93fa-0c3a39132f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ppNumericAlign ui-state-focus focus</value>
      <webElementGuid>15806b9c-f37e-4fe4-bc87-5d355792645a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>46ca50c5-27d8-48d9-9160-efcb5695eb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>58de5b9d-1971-4b4c-a02c-818ca139abc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1c285215-6bf1-4c6e-8bd8-9311dcd05ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5ea22edb-7c7f-4e0b-83bc-ef7fa1d8391a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scCreateManualSourcing_WAR_NGePportlet_:form:fileExtNo&quot;)</value>
      <webElementGuid>a979bd90-0493-478b-b0ce-272ed6947db8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_scCreateManualSourcing_WAR_NGePportlet_:form:fileExtNo']</value>
      <webElementGuid>533841bf-77f6-4877-a781-d6983f2426bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_scCreateManualSourcing_WAR_NGePportlet_:form:j_idt291_content']/table/tbody/tr[7]/td[2]/input[2]</value>
      <webElementGuid>504a28e1-6acf-4e35-8952-6a40dfe35ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[2]</value>
      <webElementGuid>55a06530-fb29-4b3c-8188-1f3ab99a5c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_scCreateManualSourcing_WAR_NGePportlet_:form:fileExtNo' and @name = '_scCreateManualSourcing_WAR_NGePportlet_:form:fileExtNo' and @type = 'text']</value>
      <webElementGuid>9c850cbe-adc8-443c-bf3a-957d34c787fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
