<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>File Reference No_1</name>
   <tag></tag>
   <elementGuidId>6c925332-9742-4bcd-8502-0541b1dbf4cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_scCreateManualSourcing_WAR_NGePportlet_:form:fileNoId']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9efb4515-c5a2-4e1f-8b28-e2961dcb0c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_scCreateManualSourcing_WAR_NGePportlet_:form:fileNoId</value>
      <webElementGuid>faaef7e0-e348-4724-ad75-64b0473dd853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_scCreateManualSourcing_WAR_NGePportlet_:form:fileNoId</value>
      <webElementGuid>e84b60a6-fdac-484b-b9a0-815583012111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb17c65f-8154-44a6-8d21-8b8258271ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>940d0949-cbcc-4aab-aa0d-7f117a5557e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus focus</value>
      <webElementGuid>177d6211-a4e3-497e-a019-a7cc4e59de65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>f5afdf63-872f-4317-91d1-1ddc2b413f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cc631415-70a2-4d59-8dc6-f5f6c7a9ebca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2f4775c-9521-453e-a5e0-171c3c256b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cce46caf-fdae-4b82-87c6-b7058a63db0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_scCreateManualSourcing_WAR_NGePportlet_:form:fileNoId&quot;)</value>
      <webElementGuid>c500634e-5ca4-4860-a255-fe605dfff9ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_scCreateManualSourcing_WAR_NGePportlet_:form:fileNoId']</value>
      <webElementGuid>5136a045-43de-426b-81a9-19ea8a775f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_scCreateManualSourcing_WAR_NGePportlet_:form:j_idt291_content']/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>dba573f5-26d7-4af8-9653-d3d28b7a5463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>6f9b19ae-5410-4c98-963a-eec1293eb573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_scCreateManualSourcing_WAR_NGePportlet_:form:fileNoId' and @name = '_scCreateManualSourcing_WAR_NGePportlet_:form:fileNoId' and @type = 'text']</value>
      <webElementGuid>0251094e-6d1f-449c-add6-d1202f106237</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
