<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Document Number</name>
   <tag></tag>
   <elementGuidId>3199d890-410d-4035-9ddd-d71880911570</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[starts-with(@id,'_BpmTaskList_WAR_NGePportlet_:form:') and contains(@id,':j_idt')])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79a4cf58-6a7b-400a-b86a-b9fd89a4526c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_BpmTaskList_WAR_NGePportlet_:form:j_idt130</value>
      <webElementGuid>2844b227-20fd-4bbb-82c7-4f17bc3e5f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_BpmTaskList_WAR_NGePportlet_:form:j_idt130</value>
      <webElementGuid>0f8bb783-2284-4ab9-8b5b-dddd1687babb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>06284a74-8745-49b1-9bbf-fc14f0a47523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>aee6aaf1-9aec-4b5c-8654-011e29a777df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus focus</value>
      <webElementGuid>71d6d9a2-8e5c-4087-b2db-f357b73c8224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>2f10366d-d024-4b30-b6f9-0d7556f61fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>de8780d1-c3d3-4845-9d79-0fbdd964c8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>36d9d7ce-2462-4456-b7c6-d36b9a79bfc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b5a810bb-7946-4cd1-ae7b-cf110a59fa8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cb0c01dd-af4a-434e-995b-0f77db1dba83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_BpmTaskList_WAR_NGePportlet_:form:j_idt130&quot;)</value>
      <webElementGuid>eb3b3861-d067-40c8-a3de-04636a46c7ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_BpmTaskList_WAR_NGePportlet_:form:j_idt130']</value>
      <webElementGuid>ee51f031-988f-4f47-8ff6-3c24eaad9e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_BpmTaskList_WAR_NGePportlet_:form:normalViewPanelId_content']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>5c5d5654-1a45-4be4-9a45-37dd14e6f496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>248c496b-c9ac-483f-b86d-75f2fca84e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_BpmTaskList_WAR_NGePportlet_:form:j_idt130' and @name = '_BpmTaskList_WAR_NGePportlet_:form:j_idt130' and @type = 'text']</value>
      <webElementGuid>1d4a31b7-6f36-4915-b065-6db421358e86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
