<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_My Task_ui-icon ui-icon-plusthick</name>
   <tag></tag>
   <elementGuidId>b482e583-7558-4e8c-92ee-5286558bf70f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='_BpmTaskList_WAR_NGePportlet_:form:normalViewPanelId_toggler']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eabf65e1-719b-499d-bc8d-50b9a523d0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-icon ui-icon-plusthick</value>
      <webElementGuid>b11ba4c2-6511-4be5-b9de-49d296aefaac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_BpmTaskList_WAR_NGePportlet_:form:normalViewPanelId_toggler&quot;)/span[@class=&quot;ui-icon ui-icon-plusthick&quot;]</value>
      <webElementGuid>8ff78304-d1a0-49af-bdfd-b8a972ad6f62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='_BpmTaskList_WAR_NGePportlet_:form:normalViewPanelId_toggler']/span</value>
      <webElementGuid>34f8300e-46a2-46c9-a287-5cee29067646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/a/span</value>
      <webElementGuid>59222ea5-1999-486a-b8a8-f6225f8912eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
